# Dashboard API Tests
@baseUrl = http://localhost:3000
@contentType = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0FkbWluIjoxLCJ1c2VySWQiOiI1ZTgyYjU2MS1kZmRmLTQwOGYtYWI4MC1hYTRhMzU4YzNmNDUiLCJ1c2VybmFtZSI6InRlc3R1c2VyIiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwicHJvZHVjdHMiOltdLCJpYXQiOjE3NjY0MTU5NzV9.SXTYzdlUJzv1sogA7oxdKKTLuHcCBsQw88nJ4GAgaME
@httptoken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0FkbWluIjoxLCJ1c2VySWQiOiI1ZTgyYjU2MS1kZmRmLTQwOGYtYWI4MC1hYTRhMzU4YzNmNDUiLCJ1c2VybmFtZSI6InRlc3R1c2VyIiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwicHJvZHVjdHMiOltdLCJpYXQiOjE3NjY0MTU5NzV9.SXTYzdlUJzv1sogA7oxdKKTLuHcCBsQw88nJ4GAgaME

@categoryId = cb76b79c-7d1d-4597-9308-2ccb23a51a0a

@productID = 3aa1f89b-1e87-498b-8084-0ec98705edc5

###
# Get categories
GET {{baseUrl}}/api/dashboard/products/categories
Cookie: token={{token}}; httpToken={{httptoken}}

###
# Create a new category
POST {{baseUrl}}/api/dashboard/products/categories
Cookie: token={{token}}; httpToken={{httptoken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Test Category2
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="category-image.png"
Content-Type: image/png

< ./public/image.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###
# update category
PUT {{baseUrl}}/api/dashboard/products/categories/{{categoryId}}
Cookie: token={{token}}; httpToken={{httptoken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

update Category2
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="category-image.png"
Content-Type: image/png

< ./public/image.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### 
# Get all products
GET {{baseUrl}}/api/dashboard/products/products
Cookie: token={{token}}; httpToken={{httptoken}}

###
# Get products by category ID
GET {{baseUrl}}/api/dashboard/products/products?categoryId={{categoryId}}
Cookie: token={{token}}; httpToken={{httptoken}}

###
# Create a new product
POST {{baseUrl}}/api/dashboard/products/products?categoryId={{categoryId}}
Cookie: token={{token}}; httpToken={{httptoken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Test Product2
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

20000
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="info"

Test product information
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

Detailed description of the test product
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="time"

60
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test-image.jpg"
Content-Type: image/png

< ./public/image.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="video"; filename="test-video.mp4"
Content-Type: video/mp4

< ./public/video.mp4
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
# Get pending comments
GET {{baseUrl}}/api/dashboard/comments
Cookie: token={{token}}; httpToken={{httptoken}}


###
# Get product offer information
GET {{baseUrl}}/api/dashboard/products/products/offer?productID={{productID}}
Cookie: token={{token}}; httpToken={{httptoken}}

###
# Update product offer
PUT {{baseUrl}}/api/dashboard/products/products/offer?productID={{productID}}
Cookie: token={{token}}; httpToken={{httptoken}}
Content-Type: {{contentType}}

{
  "exp": 24,
  "value": 15
}

###
# Get product information by ID
GET {{baseUrl}}/api/dashboard/products/products/{{productID}}
Cookie: token={{token}}; httpToken={{httptoken}}

###
# Update product information
PUT {{baseUrl}}/api/dashboard/products/products/{{productID}}
Cookie: token={{token}}; httpToken={{httptoken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Updated Product Title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

15000
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="info"

Updated product information
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

Updated detailed description of the product
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="test-image.jpg"
Content-Type: image/png

< ./public/image.png
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="video"; filename="test-video.mp4"
Content-Type: video/mp4

< ./public/video.mp4
------WebKitFormBoundary7MA4YWxkTrZu0gW--