# User API Tests
@baseUrl = http://localhost:3000
@contentType = application/json
@email = test@example.com
@password = TestPassword123
@changePassword = TestPassword123
@username = testuser
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0FkbWluIjoxLCJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6InRlc3R1c2VyIiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwicHJvZHVjdHMiOltdLCJpYXQiOjE3NjYwNzA5OTh9.JxLezpj-I8v0FFRqFdUN9A62yG9h7Xstuewh75xl7uY
@httptoken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0FkbWluIjoxLCJ1c2VySWQiOjEwLCJ1c2VybmFtZSI6InRlc3R1c2VyIiwiZW1haWwiOiJ0ZXN0QGV4YW1wbGUuY29tIiwicHJvZHVjdHMiOltdLCJpYXQiOjE3NjYwNzA5OTh9.JxLezpj-I8v0FFRqFdUN9A62yG9h7Xstuewh75xl7uY

###
# Sign Up - Send Verification Code
POST {{baseUrl}}/api/signup/send-code
Content-Type: {{contentType}}

{
  "email": "{{email}}"
}

###
# Sign Up - Verify Code and Create Account
POST {{baseUrl}}/api/signup/verify-code
Content-Type: {{contentType}}

{
  "username": "{{username}}",
  "password": "{{password}}",
  "code": 12345
}

###
# Login
POST {{baseUrl}}/api/login
Content-Type: {{contentType}}

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
# Login verify code
POST {{baseUrl}}/api/login/verify-code
Content-Type: {{contentType}}

{
  "code": "12345"
}

###
# Change Password - Send Verification Code
POST {{baseUrl}}/api/change-password
Content-Type: {{contentType}}

{
  "email": "{{email}}",
  "password": "{{changePassword}}"
}

###
# Change Password - Verify Code and Set New Password
PUT {{baseUrl}}/api/change-password
Content-Type: {{contentType}}

{
  "code": 12345
}

###
# Change User Characteristics - Send Verification Code
POST {{baseUrl}}/api/profile/change-characteristics
Cookie: token={{token}}; httpToken={{httptoken}}
Content-Type: {{contentType}}

{
  "password": "{{password}}"
}

###
# Change User Characteristics - Verify Code and Update Info
PUT {{baseUrl}}/api/profile/change-characteristics
Cookie: token={{token}}; httpToken={{httptoken}}
Content-Type: {{contentType}}

{
  "code": "12345",
  "username": "updatedusername",
  "newPassword": "{{{{changePassword}}}}"
}

###
# Upload Profile Image
POST {{baseUrl}}/api/profile/image
Cookie: token={{token}}; httpToken={{httptoken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.png"
Content-Type: image/jpeg

< public/image.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
# Get Profile Image
GET {{baseUrl}}/api/profile/image
Cookie: token={{token}}; httpToken={{httptoken}}

###
# Get User Purchases
GET {{baseUrl}}/api/profile/my-purchases
Cookie: token={{token}}; httpToken={{httptoken}}

###
# Logout
POST {{baseUrl}}/api/profile/logout
Cookie: token={{token}}; httpToken={{httptoken}}