# Product API Tests
@baseUrl = http://localhost:3000
@filename = 1jd3kce6vtest-video_1_0_.mp4
@contentType = application/json
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0FkbWluIjoxLCJ1c2VySWQiOiI2NmIzNjg2YS1hMmUxLTQ0NmMtODc0YS1kMjNhOTJlNWM1MDIiLCJ1c2VybmFtZSI6InRlc3R1c2VyIiwiZW1haWwiOiJ0ZXN0MUBleGFtcGxlLmNvbSIsInByb2R1Y3RzIjpbXSwiaWF0IjoxNzY2NTg2ODA0fQ.3jz8cdl48x3Em6Hgutd4cTi1FC94LncSQVHSm8N4cAg
@httptoken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0FkbWluIjoxLCJ1c2VySWQiOiI2NmIzNjg2YS1hMmUxLTQ0NmMtODc0YS1kMjNhOTJlNWM1MDIiLCJ1c2VybmFtZSI6InRlc3R1c2VyIiwiZW1haWwiOiJ0ZXN0MUBleGFtcGxlLmNvbSIsInByb2R1Y3RzIjpbXSwiaWF0IjoxNzY2NTg2ODA0fQ.3jz8cdl48x3Em6Hgutd4cTi1FC94LncSQVHSm8N4cAg
@categoryId = b51eba18-44ca-4e97-a403-2bea04cac168
@productID = 80c55466-a17e-4a31-be67-ec5844603f4d
@commentId = c6d72694-d3a1-4cee-9091-0004bb8e3bd2

###
# Get all categories
GET {{baseUrl}}/api/categories

###
# Get all products
GET {{baseUrl}}/api/products

###
# Get products by category ID
GET {{baseUrl}}/api/products?categoryId={{categoryId}}

###
# Search products by keyword
POST {{baseUrl}}/api/products/search-all
Content-Type: {{contentType}}

{
  "text": "2"
}

###
# Get a specific product by ID
GET {{baseUrl}}/api/products/{{productID}}

###
# Get product comments by product ID
GET {{baseUrl}}/api/products/comments?productID={{productID}}

###
# Add a new comment to a product
POST {{baseUrl}}/api/products/comments?productID={{productID}}
Cookie: token={{token}}; httpToken={{httptoken}}
Content-Type: {{contentType}}

{
  "message": "عالی بود۳!",
  "rating": 5
}

###
# Get comment details by comment ID
GET {{baseUrl}}/api/products/comments/{{commentId}}

###
# Update a comment
PUT {{baseUrl}}/api/products/comments/{{commentId}}
Cookie: token={{token}}; httpToken={{httptoken}}
Content-Type: {{contentType}}

{
  "message": "بعد از ویرایش عالی شد!",
  "star": 4
}

###
#show user comment
PUT {{baseUrl}}/api/products/comments/show?commentID={{commentId}}
Cookie: token={{token}}; httpToken={{httptoken}}
Content-Type: {{contentType}}

###
# Get offer products
GET {{baseUrl}}/api/products/offers

###
# Stream a product video
GET {{baseUrl}}/api/products/videos?filename={{filename}}

### Test Payment Confirmation
GET {{baseUrl}}/api/payment/confirm/{{productID}}
Cookie: token={{token}}; httpToken={{httptoken}}
Content-Type: {{contentType}}